# Generated by Django 4.2 on 2023-04-14 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_like_b_blog_like_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='author',
            new_name='like_author',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='blog',
            new_name='like_blog',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='like_b',
        ),
    ]
