# Generated by Django 4.2 on 2023-04-14 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_author_like_like_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='like_author',
            new_name='author',
        ),
        migrations.AddField(
            model_name='blog',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='likes', to='blog.like'),
        ),
        migrations.AlterField(
            model_name='like',
            name='like_blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='blog.blog'),
        ),
    ]
